substitutions:
  _IMAGE_NAME: 'gcr.io/${_PROJECT_ID}/my-app'
  _TAG_NAME: '0.0.1'
  _REGION: 'us-central1'  # Replace with your preferred region.
  _SERVICE_NAME: 'my-first-service'  # Replace with your preferred Cloud Run service name.
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Connect to instance
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      echo "$$ssh_private_kei" > deploy.key
      chmod 600 deploy.key
      ssh -T -o StrictHostKeyChecking=no -i deploy.key Rija@34.135.197.43 /bin/bash <<'EOT'
      echo "These commands will be run on: $( uname -a )"
      echo "They are executed by: $( whoami )"
      EOT
    secretEnv: ['ssh_private_kei']
availableSecrets:
  secretManager:
  - versionName: projects/418744326158/secrets/Rija/versions/latest
    env: 'ssh_private_kei'
      
#images:
#  - 'us-central1-docker.pkg.dev/vibrant-petal-406618/my-registre/nodes:latest'  # Reference the dynamic image name and tag.
