steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'us-docker.pkg.dev/vibrant-petal-406618/testa-artf/nodesss'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-docker.pkg.dev/vibrant-petal-406618/testa-artf/nodesss:latest'
