substitutions:
  _IMAGE_NAME: 'gcr.io/${_PROJECT_ID}/my-app'
  _TAG_NAME: '0.0.1'
  _REGION: 'us-central1'  # Replace with your preferred region.
  _SERVICE_NAME: 'my-first-service'  # Replace with your preferred Cloud Run service name.
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Connect to instance
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      telnet 34.69.44.29 22 
      ssh -i id_rsa_test Rija@34.69.44.29
      
#images:
#  - 'us-central1-docker.pkg.dev/vibrant-petal-406618/my-registre/nodes:latest'  # Reference the dynamic image name and tag.
